version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
