sonar.sources=src
sonar.tests=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,src/vite-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.node.json
sonar.sourceEncoding=UTF-8
