import { test, expect, type Browser, type Page, type APIRequestContext } from '@playwright/test'

const password = 'Test-Only-September-2026!'
async function register(browser: Browser, request: APIRequestContext, email: string): Promise<Page> {
  const context = await browser.newContext()
  const page = await context.newPage()
  await page.goto('/')
  await page.getByRole('link', { name: /Register/ }).click()
  await page.locator('#firstName').fill('Test')
  await page.locator('#lastName').fill(email.split('@')[0])
  await page.locator('#email').fill(email)
  if (await page.locator('#password').count()) {
    await page.locator('#password').fill(password)
    await page.locator('#password-confirm').fill(password)
  }
  await page.getByRole('button', { name: /Register/ }).click()
  await expect(page.getByText(/verify your email|verification email|verify email/i).first()).toBeVisible()
  let messageId = ''
  await expect.poll(async () => {
    const response = await request.get('http://localhost:28025/api/v1/messages')
    const mail = await response.json()
    const message = mail.messages.find((m: { To: { Address: string }[] }) => m.To.some(to => to.Address === email))
    messageId = message?.ID ?? ''
    return messageId
  }).not.toBe('')
  // Open the captured verification email in Mailpit's actual web interface.
  const inbox = await context.newPage()
  await inbox.goto('http://localhost:28025/')
  await expect(inbox.getByText(/verify|verification/i).first()).toBeVisible()
  await inbox.getByText(/verify|verification/i).first().click()
  const mail = await (await request.get('http://localhost:28025/api/v1/message/' + messageId)).json()
  const link = (mail.Text as string).match(/http:\/\/localhost:28180\/[^\s<>]+/)
  expect(link).not.toBeNull()
  await page.goto(link![0].replaceAll('&amp;', '&'))
  const proceed = page.getByRole('link', { name: /proceed|back to application/i })
  if (await proceed.count()) await proceed.first().click()
  await expect(page.locator('#password-new')).toBeVisible()
  await page.locator('#password-new').fill(password)
  await page.locator('#password-confirm').fill(password)
  await page.getByRole('button', { name: /Submit/ }).click()
  await page.goto('/')
  if (await page.locator('#username').count()) {
    await page.locator('#username').fill(email)
    await page.locator('#password').fill(password)
    await page.getByRole('button', { name: /Sign In/ }).click()
  }
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  return page
}

test('source reader keyboard navigation and mobile layout', async ({ browser, request }, testInfo) => {
  const owner = await register(browser, request, 'reader-' + Date.now() + '@example.local')
  await owner.getByLabel('Nombre del universo').fill('El Meridiano de Ceniza')
  await owner.getByRole('button', { name: 'Crear universo' }).click()
  await owner.getByRole('combobox', { name: 'Visibilidad', exact: true }).selectOption({ label: 'Público · Pública' })
  await owner.getByLabel('Título', { exact: true }).fill('El Meridiano y Lumbrevela')
  await owner.getByLabel('Archivo Markdown o TXT').setInputFiles('../demo/lore/public/01-el-meridiano-y-lumbrevela.md')
  await owner.getByRole('button', { name: 'Subir y procesar' }).click()
  const trigger = owner.getByRole('button', { name: 'Leer El Meridiano y Lumbrevela' })
  await expect(trigger).toBeVisible({ timeout: 60_000 })
  await trigger.click()
  const reader = owner.getByRole('article', { name: 'Fuente: El Meridiano y Lumbrevela' })
  const close = reader.getByRole('button', { name: 'Cerrar fuente' })
  await expect(reader.getByRole('heading', { name: 'El Meridiano y Lumbrevela' })).toBeFocused()
  await owner.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await close.click()
  await expect(reader).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await owner.screenshot({ path: testInfo.outputPath('library-original-corpus.png'), fullPage: true })
  await owner.setViewportSize({ width: 390, height: 844 })
  if (await owner.getByRole('button', { name: 'Abrir índice' }).isVisible()) await owner.getByRole('button', { name: 'Abrir índice' }).click()
  await trigger.click()
  await expect(reader).toContainText('Lumbrevela se alza al este del Meridiano')
  expect(await owner.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await owner.screenshot({ path: testInfo.outputPath('reader-original-mobile.png') })
  await owner.context().close()
})

test('verified owner and two players: realms, library, invitation, recovery and literal evidence', async ({ browser, request }, testInfo) => {
  const suffix = Date.now().toString()
  const owner = await register(browser, request, 'owner-' + suffix + '@example.local')
  await owner.getByLabel('Nombre del universo').fill('Universo ' + suffix)
  await owner.getByRole('button', { name: 'Crear universo' }).click()
  const players = ['one-', 'two-'].map(prefix => prefix + suffix + '@example.local')
  await owner.getByRole('button', { name: 'Personas y permisos' }).click()
  for (const email of players) {
    await owner.getByLabel('Correo del jugador').fill(email)
    await owner.getByRole('button', { name: 'Invitar', exact: true }).click()
    await expect(owner.getByText(email).first()).toBeVisible()
  }
  const one = await register(browser, request, players[0])
  const two = await register(browser, request, players[1])
  for (const player of [one, two]) {
    await expect(player.getByLabel('Universo activo')).toHaveValue(await owner.getByLabel('Universo activo').inputValue())
    await expect(player.getByRole('region', { name: 'Procesamiento de fuentes' })).toHaveCount(0)
    await expect(player.getByLabel('Archivo Markdown o TXT')).toHaveCount(0)
  }
  await request.post('http://localhost:21434/test/failures', { data: { count: 1 } })
  await owner.getByRole('button', { name: 'Fuentes', exact: true }).click()
  const literal = 'Nara no entregó las 37 monedas el 2 de mayo de 2024. Áurea conserva 1.250 € y una brújula 🧭.'
  await owner.getByRole('combobox', { name: 'Visibilidad', exact: true }).selectOption({ label: 'Público · Pública' })
  await owner.getByLabel('Título', { exact: true }).fill('Crónica verificable')
  await owner.getByLabel('Archivo Markdown o TXT').setInputFiles({ name: 'cronica.md', mimeType: 'text/markdown', buffer: Buffer.from('# Nara\n\n' + literal) })
  await owner.getByRole('button', { name: 'Subir y procesar' }).click()
  await expect(owner.getByText(/El modelo no respondió/)).toBeVisible()
  await expect(owner.getByText('Operaciones finalizadas (1)', { exact: true })).toBeVisible({ timeout: 60_000 })
  await owner.getByText('Operaciones finalizadas (1)', { exact: true }).click()
  await expect(owner.locator('.source-job > p').filter({ hasText: /^Completado/ }).first()).toBeVisible()
  // Missing or incompatible output produces a visible failure without hiding the published version.
  await request.post('http://localhost:21434/test/failures', { data: { count: 3 } })
  await owner.getByText('Gestionar', { exact: true }).click()
  await owner.getByLabel('Reemplazar archivo de Crónica verificable').setInputFiles({ name: 'cronica.md', mimeType: 'text/markdown', buffer: Buffer.from('# Nara\n\n' + literal + ' Sigue vigente.') })
  await expect(owner.locator('.source-job > p').filter({ hasText: /^Necesita atención/ }).first()).toBeVisible({ timeout: 180_000 })
  await expect(owner.getByText('La versión 1 sigue publicada y disponible para consultas.').first()).toBeVisible()
  await owner.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(owner.locator('.source-job > p').filter({ hasText: /^Completado/ })).toHaveCount(2)
  for (const player of [one, two]) {
    await player.reload()
    // Library use does not depend on a successful model answer.
    await player.getByLabel('Buscar fuentes').fill('cronica.md')
    const readSource = player.getByRole('button', { name: 'Leer Crónica verificable' })
    await readSource.click()
    const reader = player.getByRole('article', { name: 'Fuente: Crónica verificable' })
    await expect(reader).toContainText(literal + ' Sigue vigente.')
    // The inline reader moves focus to its title and returns to the index on close.
    await expect(reader.getByRole('heading', { name: 'Crónica verificable' })).toBeFocused()
    await player.keyboard.press('Tab')
    await expect(reader.getByRole('button', { name: 'Cerrar fuente' })).toBeFocused()
    await reader.getByRole('button', { name: 'Cerrar fuente' }).click()
    await expect(reader).toHaveCount(0)
    await expect(readSource).toBeFocused()
    await player.getByLabel('Buscar fuentes').fill('sin coincidencias')
    await expect(readSource).toHaveCount(0)
    await player.getByLabel('Buscar fuentes').fill('CRONICA')
    await expect(readSource).toBeVisible()
    await player.getByRole('button', { name: 'Consultas', exact: true }).click()
    await player.getByLabel('¿Qué quieres saber?').fill('Nara monedas')
    await player.getByRole('button', { name: 'Consultar', exact: true }).click()
    await expect(player.locator('blockquote')).toHaveText(literal + ' Sigue vigente.')
    await player.getByRole('button', { name: 'Abrir contexto [1]' }).click()
    await expect(player.getByRole('dialog')).toContainText(literal + ' Sigue vigente.')
    // Citation dialogs keep the native keyboard loop and exact context reader.
    await expect(player.getByRole('button', { name: 'Cerrar evidencia' })).toBeFocused()
    await player.keyboard.press('Shift+Tab')
    await expect(player.getByRole('dialog').getByLabel('Contenido de la fuente')).toBeFocused()
    await player.keyboard.press('Tab')
    await expect(player.getByRole('button', { name: 'Cerrar evidencia' })).toBeFocused()
    await player.getByRole('button', { name: 'Leer documento completo' }).click()
    await expect(player.getByLabel('Contenido de la fuente')).toHaveText('# Nara\n\n' + literal + ' Sigue vigente.')
    await player.keyboard.press('Escape')
  }
  const firstRealm = await owner.getByLabel('Universo activo').inputValue()
  await owner.getByRole('button', { name: 'Nuevo universo', exact: true }).click()
  await owner.getByLabel('Nombre del universo').fill('Segunda campaña ' + suffix)
  await owner.getByRole('button', { name: 'Crear universo' }).click()
  await expect(owner.getByLabel('Universo activo')).not.toHaveValue(firstRealm)
  await expect(owner.getByRole('button', { name: 'Leer Crónica verificable' })).toHaveCount(0)
  await owner.getByText('Propietario · Cambiar universo', { exact: true }).click()
  await owner.getByLabel('Universo activo').selectOption(firstRealm)
  await expect(owner.getByRole('button', { name: 'Leer Crónica verificable' })).toBeVisible()
  await owner.screenshot({ path: testInfo.outputPath('library-desktop.png'), fullPage: true })
  await one.setViewportSize({ width: 390, height: 844 })
  await one.getByRole('button', { name: 'Fuentes', exact: true }).click()
  if (await one.getByRole('button', { name: 'Abrir índice' }).isVisible()) await one.getByRole('button', { name: 'Abrir índice' }).click()
  await one.getByRole('button', { name: 'Leer Crónica verificable' }).click()
  await expect(one.getByRole('article', { name: 'Fuente: Crónica verificable' })).toBeVisible()
  expect(await one.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await one.screenshot({ path: testInfo.outputPath('reader-mobile.png') })
  await owner.context().close(); await one.context().close(); await two.context().close()
})
